export const FETCH_PEOPLES = 'FETCH_PEOPLES';
export const CREATE_PEOPLE = 'CREATE_PEOPLE';
export const PEOPLES_HAS_ERRORED = 'PEOPLES_HAS_ERRORED';
export const PEOPLES_IS_LOADING = 'PEOPLES_IS_LOADING';