export const GET_PEOPLES_FETCH = 'GET_PEOPLES_FETCH';
export const GET_PEOPLES_SUCCESS = 'GET_PEOPLE_SUCCESS';

export const HAS_ERROR = 'HAS_ERROR';
export const IS_FETCHING = 'IS_FETCHING';

export const CREATE_PEOPLE = 'CREATE_PEOPLE';
export const CREATE_PEOPLE_SUCCESS = 'CREATE_PEOPLE_SUCCESS';

export const EDIT_PEOPLE = 'EDIT_PEOPLE';
export const EDIT_PEOPLE_SUCCESS = 'EDIT_PEOPLE_SUCCESS';

export const DELETE_PEOPLE = 'DELETE_PEOPLE';
export const DELETE_PEOPLE_SUCCESS = 'DELETE_PEOPLE_SUCCESS';
